#!/bin/bash

CUR=`dirname $0`
INPUTDIR=$CUR/../tmp
TARGETDIR=$CUR/../catalogo
SAXON=$CUR/saxon-he-10.5.jar
XSL=$CUR/catalogo_to_html.xsl


# fetch catalogo TEI XML
#wget https://raw.githubusercontent.com/pulibrary/cicognara-catalogo/main/catalogo.tei.xml -P $DATADIR

# generate HTML
java -cp  $SAXON net.sf.saxon.Transform -s:$INPUTDIR/catalogo.tei.xml -xsl:$XSL -o:$TARGETDIR/index.html
