#!/bin/bash

CUR=`dirname $0`
INPUTDIR=$CUR/../data
TARGETDIR=$CUR/../apps/cicognara-static/catalogo
# SAXON=$CUR/saxon-he-10.5.jar
SAXON=$CUR/saxon-he-12.4.jar
XSL=$CUR/catalogo_to_html.xsl


java -cp  $SAXON net.sf.saxon.Transform -s:$INPUTDIR/catalogo.tei.xml -xsl:$XSL -o:$TARGETDIR/index.html
